### PR TITLE
Refactor UI and enhance memory management

### PR DESCRIPTION
**Pull request by pictos**
- Updated AppShell.xaml to load `FirstPage` as the initial page, with minor formatting adjustments.
- Disabled nullable reference types in the project file to change compiler nullability checks.
- Added `OnNavigatedFrom` in MainPage.xaml.cs to force garbage collection when navigating away, and introduced a new `FirstPage` class with a method to explicitly call garbage collection.
- MainPageViewModel.cs now uses a `WeakReference<Timer>` for better memory management, added a new `Timer` property for encapsulated access, and updated the destructor with a comment on finalizer execution.
- Minor unchanged functionality in `ImageGenerator` class, indicating a focus on memory management and performance improvements.

### CODE REVIEW

**Comment by PickleBurg** [comment]
This seems to limit the memory growth but it seams the timer is not updating 60 fps

**Comment by pictos** [comment]
Another approach is to not use WeakReference, but make sure to call the Timer.Dispose manually

**Comment by PickleBurg** [comment]
I've just committed a change which cleans the memory when the page is navigated away but in the use case of lets say an 8 hour camera session is there a way to dispose and activate the timer to do a memory clean without disposing the whole view model

**Comment by pictos** [comment]
Yeah, it's possible... But you will need to refactor the code. Splitting in a method what you want to clean up and restart again. That shouldn't me too hard... Maybe refactoring the bitmap/timer code to another class that will handle that

**Pull request merged**
